pub fn apply_constructor(
    name: &str,
    args: &[Arg],
    var_gen: &mut VarGen,
) -> Result<SemValue, String> {
    match name {
        "the_dp" => construct_quant_dp(DpQuantKind::The, args, var_gen),
        "exists_dp" => construct_quant_dp(DpQuantKind::Exists, args, var_gen),
        "forall_dp" => construct_quant_dp(DpQuantKind::ForAll, args, var_gen),
        "bare_dp" => construct_bare_dp(args),
        "bare_n" => construct_bare_n(args, var_gen),
        "adj_n" => construct_adj_n(args, _var_gen),
        "the_n_dp" => construct_the_n_dp(args),
        "a_n_dp" => construct_a_n_dp(args),
        "the_of_dp" => construct_the_of_dp(args, var_gen),
        "s_copula" => construct_s_copula(args),
        "s_copula_adj_n" => construct_s_copula_adj_n(args),
        "s_equative" => construct_s_equative(args),
        "s_transitive" => construct_s_transitive(args),
        "s_ditransitive" => construct_s_ditransitive(args),
        "s_complement" => construct_s_complement(args),
        "s_gap_agent" => construct_s_gap("agent", "patient", args, var_gen),
        "s_gap_patient" => construct_s_gap("patient", "agent", args, var_gen),
        "s_gap_theme" => construct_s_gap_theme(args, var_gen),
        "rel_dp_agent" => construct_rel_dp("agent", args, var_gen),
        "rel_dp_patient" => construct_rel_dp("patient", args, var_gen),
        "rel_dp_theme" => construct_rel_dp("theme", args, var_gen),
        _ => Err(format!("unknown constructor: {}", name)),
    }
}